<a href="https://colab.research.google.com/github/DjengoFang/Financial-Engineering-Ruppert-Matteson-/blob/main/Lab5.19.2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import scipy.stats as stats
import scipy.optimize as opt
import statsmodels.api as sm
import pylab as py
import seaborn as sns

In [19]:
!pip install fitter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [20]:
from fitter import Fitter, get_common_distributions, get_distributions

In [21]:
url = 'https://raw.githubusercontent.com/DjengoFang/Financial-Engineering-Ruppert-Matteson-/main/datasets/EuStockMarkets.csv'
data = pd.read_csv(url)
data.head(5)

DAX     SMI     CAC    FTSE
0  1628.75  1678.1  1772.8  2443.6
1  1613.63  1688.5  1750.5  2460.2
2  1606.51  1678.6  1718.0  2448.2
3  1621.04  1684.1  1708.1  2470.4
4  1618.16  1686.6  1723.1  2484.7

In [22]:
DAX_log = np.diff(np.log(data['DAX']))
DAX_log

array([-0.00932655, -0.00442218,  0.00900379, ...,  0.01895731,
       -0.0059412 ,  0.02192215])

# Problem 6

In [23]:
x = DAX_log

def log_like(parameters):
  f = -np.sum(stats.t.logpdf(x,parameters[2],parameters[0],parameters[1]))
  return f

In [24]:
start = np.array([np.mean(x), np.std(x), 4])
bnds = ((-0.1,0.1), (0.001, 1), (2.1, 20))
log_like_model = opt.minimize(fun=log_like, x0=start, method='L-BFGS-B',bounds=bnds) 

## Optimize Parameters

In [25]:
parm = log_like_model.x
print(parm)

[7.84723297e-04 7.53880850e-03 4.19454353e+00]


## AIC  Akaike information criterion

In [26]:
minus_logL_std = log_like(parm)
print(minus_logL_std)

-5983.321865930821


In [27]:
AIC_std = 2*minus_logL_std + 2*len(parm)
print(AIC_std)

-11960.643731861643


# Problem 7

In [28]:
!pip install sstudentt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [29]:
from sstudentt import SST

In [30]:
def log_like_SST(parameters):
  dist = SST(mu = parameters[0], sigma = parameters[1], nu = parameters[2], tau = parameters[3])
  f = -np.sum(np.log(SST.p(x)))
  return f

In [31]:
start = np.array([np.mean(x), np.std(x), 4, 1])
bnds = ((-0.1,0.1), (0.001, 1), (2.1, 20), (0.25, 4))
log_like_model = opt.minimize(fun=log_like, x0=start, method='L-BFGS-B',bounds=bnds) 

## Optimize Parameters

In [32]:
parm2 = log_like_model.x
print(parm2)

[7.84723297e-04 7.53880850e-03 4.19454353e+00 1.00000000e+00]


## AIC  Akaike information criterion

In [33]:
minus_logL_std = log_like(parm2)
print(minus_logL_std)
AIC_std = 2*minus_logL_std + 2*len(parm2)
print(AIC_std)

-5983.321865930821
-11958.643731861643
